@extends('frontend/new-master')
@section('title', 'Facilities : The Assam Royal Global University')
@section('meta_description',
    'Explore world-class facilities at Royal Global University, including modern classrooms,
    advanced laboratories, sports complexes, libraries, and student-friendly campus amenities.')
@section('meta_keywords', 'Facilities')
@section('content')
    <style>
        /*==================================================
    FACILITIES
    ==================================================*/

        .rgfacilities-section {
            padding: 70px 0;
            background: #edf4ff;
        }


        /*==================================================
    CARD
    ==================================================*/

        .rgfacility-card {
            background: #ffffff;
            border-radius: 8px;
            padding: 14px;
            height: 100%;
            transition: .35s ease;
        }

        .rgfacility-card:hover {
            transform: translateY(-6px);
            box-shadow: 0 14px 35px rgba(0, 0, 0, .08);
        }


        /*==================================================
    IMAGE
    ==================================================*/

        .rgfacility-image {
            overflow: hidden;
            border-radius: 6px;
        }

        .rgfacility-image img {
            width: 100%;
            aspect-ratio: 16/10;
            object-fit: cover;
            display: block;
            transition: .45s ease;
        }

        .rgfacility-card:hover .rgfacility-image img {
            transform: scale(1.05);
        }


        /*==================================================
    CONTENT
    ==================================================*/

        .rgfacility-content {
            padding-top: 18px;
        }

        .rgfacility-content h3 {
            font-size: 30px;
            font-weight: 700;
            color: #27467d;
            line-height: 1.35;
            margin-bottom: 18px;
        }


        /*==================================================
    BUTTON
    ==================================================*/

        .rgfacility-btn {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            background: #e86b2f;
            color: #ffffff;
            text-decoration: none;
            font-size: 13px;
            font-weight: 600;
            padding: 10px 18px;
            border-radius: 4px;
            transition: .3s ease;
        }

        .rgfacility-btn:hover {
            background: #27467d;
            color: #ffffff;
            text-decoration: none;
        }


        /*==================================================
    RESPONSIVE
    ==================================================*/

        @media (max-width:991px) {

            .rgfacilities-section {
                padding: 60px 0;
            }

            .rgfacility-content h3 {
                font-size: 24px;
            }

        }

        @media (max-width:767px) {

            .rgfacilities-section {
                padding: 50px 0;
            }

            .rgfacility-card {
                padding: 12px;
            }

            .rgfacility-content {
                padding-top: 15px;
            }

            .rgfacility-content h3 {
                font-size: 22px;
                margin-bottom: 15px;
            }

            .rgfacility-btn {
                width: 100%;
            }

        }
    </style>

    <section class="pg-hero">
        <div class="pg-hero-bg" style="background-image:url('new-web/assets/img/anti-ragging/cover.png'); filter: blur(5px);">
        </div>

        <div class="pg-hero-bg"></div>
        <div class="pg-hero-overlay"></div>

        <div class="pg-hero-inner">
            <h1 class="pg-hero-title"> Facilities</h1>
            <div class="pg-hero-breadcrumb">
                Discover RGU / Campus and Students Life / Facilities
            </div>
        </div>

    </section>

    <section class="rgfacilities-section">

        <div class="container">

            <div class="row" id="rgFacilitiesCards">

                <!-- Generated by JavaScript -->

            </div>

        </div>

    </section>

    <script>
        const facilities = [

            {
                title: "Auditorium",
                image: "https://media.rgu.ac/facilities/Auditorium.jpg",
                link: "https://rgu.ac/facilities-auditorium"
            },

            {
                title: "Banking Services",
                image: "https://media.rgu.ac/facilities/BankingServices.webp",
                link: "https://rgu.ac/banking-services"
            },

            {
                title: "Classrooms and Studios",
                image: "https://media.rgu.ac/facilities/ClassroomStudio.jpg",
                link: "https://rgu.ac/facilities-classroom"
            },

            {
                title: "Diagnostic Centre",
                image: "https://media.rgu.ac/facilities/DignosticCenter.JPG",
                link: "https://rgu.ac/facilities-diagnostic"
            },

            {
                title: "Fine Arts Studio",
                image: "https://media.rgu.ac/facilities/FineArtsStudio.jpg",
                link: "https://rgu.ac/facilities-fineart"
            },

            {
                title: "Fashion Studio",
                image: "https://media.rgu.ac/facilities/FashionStudio.png",
                link: "https://rgu.ac/facilities-fashion-studio"
            },

            {
                title: "Games and Sports",
                image: "https://media.rgu.ac/facilities/games.jpg",
                link: "https://rgu.ac/games&sports"
            },

            {
                title: "Food Court",
                image: "https://media.rgu.ac/facilities/Hangouts.jpg",
                link: "https://rgu.ac/facilities-foodcourt"
            },

            {
                title: "Incubation Centre",
                image: "https://media.rgu.ac/facilities/IncubationCenter.JPG",
                link: "https://rgu.ac/facilities-incubation"
            },

            {
                title: "Laboratories",
                image: "https://media.rgu.ac/facilities/Laboratories.JPG",
                link: "https://rgu.ac/laboratories"
            },

            {
                title: "Library",
                image: "https://media.rgu.ac/facilities/Library.png",
                link: "https://rgu.ac/library-Resources"
            },

            {
                title: "Legal Aid",
                image: "https://media.rgu.ac/facilities/LegalAid.jpg",
                link: "https://rgu.ac/facilities-legal-aid"
            },

            {
                title: "Medical Facility",
                image: "https://media.rgu.ac/facilities/MedicalFacility.JPG",
                link: "https://rgu.ac/medical-facility"
            },

            {
                title: "Moot Court",
                image: "https://media.rgu.ac/facilities/MootCourt.jpg",
                link: "https://rgu.ac/facilities-moot-court"
            },

            {
                title: "Mass Comm Studio",
                image: "https://media.rgu.ac/facilities/MassComStudio-07.png",
                link: "https://rgu.ac/facilities-mass-com"
            },

            {
                title: "Royal Boutique",
                image: "https://media.rgu.ac/facilities/TheRoyalBoutique.JPG",
                link: "https://rgu.ac/facilities-royal-boutique"
            },

            {
                title: "Salon",
                image: "https://media.rgu.ac/facilities/Salon.JPG",
                link: "https://rgu.ac/facilities-salon"
            },

            {
                title: "Stationary Store",
                image: "https://media.rgu.ac/facilities/StationaryStore.jpg",
                link: "https://rgu.ac/stationary-store"
            },

            {
                title: "Student Gallery",
                image: "https://media.rgu.ac/facilities/StudentGallery.JPG",
                link: "https://rgu.ac/student-gallery"
            },

            {
                title: "Security and Surveillance",
                image: "https://media.rgu.ac/facilities/Security.JPG",
                link: "https://rgu.ac/facilities-security"
            },

            {
                title: "Conference & Seminar Halls",
                image: "https://media.rgu.ac/facilities/SeminarHalls.png",
                link: "https://rgu.ac/facilities-seminar-hall"
            },

            {
                title: "Hangout & Student Lounge",
                image: "https://media.rgu.ac/facilities/StudentLounge.jpg",
                link: "https://rgu.ac/facilities-student-lounge"
            },

            {
                title: "Transportation",
                image: "https://media.rgu.ac/facilities/Transportation.jpg",
                link: "https://rgu.ac/facilities-transportation"
            },

            {
                title: "Dr. Bhupen Hazarika - Centre for Creativity",
                image: "https://rgu.ac/mobile-assets/facilities/bhupen.jpeg",
                link: "https://rgu.ac/bhupen-hazarika-CFC"
            },

            {
                title: "University Museum",
                image: "https://media.rgu.ac/facilities/UniversityMuseum.jpg",
                link: "https://rgu.ac/facilities-museum"
            }

        ];
    </script>

    <script>
        /*==================================================
    CREATE FACILITY CARD
    ==================================================*/

        function createFacilityCard(facility) {

            return `

        <div class="col-xl-4 col-lg-4 col-md-6 mb-4">

            <div class="rgfacility-card">

                ${facility.image ? `
                        <div class="rgfacility-image">

                            <img
                                src="${facility.image}"
                                alt="${facility.title}"
                            >

                        </div>
                    ` : ""}

                <div class="rgfacility-content">

                    ${facility.title ? `
                            <h3>
                                ${facility.title}
                            </h3>
                        ` : ""}

                    ${facility.link ? `
                            <a
                                href="${facility.link}"
                                class="rgfacility-btn"
                            >
                                Explore More
                            </a>
                        ` : ""}

                </div>

            </div>

        </div>

    `;

        }


        /*==================================================
        RENDER FACILITIES
        ==================================================*/

        function renderFacilities() {

            const container = document.getElementById("rgFacilitiesCards");

            if (!container || typeof facilities === "undefined") return;

            container.innerHTML = facilities
                .map(createFacilityCard)
                .join("");

        }


        /*==================================================
        INITIALIZE
        ==================================================*/

        document.addEventListener("DOMContentLoaded", () => {

            renderFacilities();

        });
    </script>
@endsection
