@extends('frontend/new-master')
@section('title', 'Royal Frootprints : The Assam Royal Global University')
@section('meta_description', 'Follow the royal footprints of success with Royal Global University Royal Footprints.')
@section('meta_keywords', 'Royal Frootprints')
@section('content')
    <section class="pg-hero">
        <div class="pg-hero-bg"
            style="background-image:url('/new-web/assets/img/Discover-RGU-About-the-University-Royal-Footprints/cover.png'); filter: blur(2px);">
        </div>

        <div class="pg-hero-bg"></div>
        <div class="pg-hero-overlay"></div>

        <div class="pg-hero-inner">
            <h1 class="pg-hero-title">Royal Footprints</h1>
            <div class="pg-hero-breadcrumb">
                Discover RGU / About the University / Royal Footprints
            </div>
        </div>

    </section>

    <!-- ======================================
             ROYAL FOOTPRINTS
        ====================================== -->

    <section class="rgu-rf-section">

        <div class="container">

            <!-- Quote Section -->

            <div class="rgu-rf-quote-wrap">

                <div class="rgu-rf-quote-icon">
                    <i class="fa fa-quote-left"></i>
                </div>

                <blockquote class="rgu-rf-quote">

                    We want that education by which character is formed,
                    strength of mind is increased, the intellect is expanded,
                    and by which one can stand on one's own feet.

                </blockquote>

                <div class="rgu-rf-quote-author">
                    Swami Vivekananda
                </div>

            </div>

        </div>


        <!-- Blue Section -->

        <div class="rgu-rf-showcase">

            <div class="container">

                <div class="row">

                    <!-- Left Tabs -->

                    <div class="col-lg-3">

                        <div class="rgu-rf-tabs" id="rguRfTabs">

                            <!-- Generated by JS -->

                        </div>

                    </div>


                    <!-- Right Content -->

                    <div class="col-lg-9">

                        <div class="rgu-rf-content">


                            <!-- Cards -->

                            <div class="row g-4" id="rguRfCards">

                                <!-- Generated by JS -->

                            </div>


                            <!-- Pagination -->

                            <div class="rgu-rf-pagination-wrap">

                                <div class="rgu-rf-pagination" id="rguRfPagination">

                                    <!-- Generated by JS -->

                                </div>

                            </div>


                        </div>

                    </div>

                </div>

            </div>

        </div>

    </section>

    <style>
        /*======================================
        ROYAL FOOTPRINTS
        ======================================*/

        .rgu-rf-section {
            background: #eef3f8;
        }


        /*======================================
        QUOTE SECTION
        ======================================*/

        .rgu-rf-quote-wrap {
            max-width: 1000px;
            margin: 0 auto;
            text-align: center;
            padding: 7rem 0 9rem;
        }

        .rgu-rf-quote-icon {
            margin-bottom: 2rem;
        }

        .rgu-rf-quote-icon i {
            color: #d95b28;
            font-size: 5rem;
        }

        .rgu-rf-quote {
            max-width: 850px;
            margin: 0 auto 3rem;

            font-family: 'Playfair Display', serif;
            font-size: 3.8rem;
            font-weight: 700;
            line-height: 1.5;
            font-style: normal;

            color: #2f4e89;
        }

        .rgu-rf-quote-author {
            font-family: 'Times New Roman', Times, serif;
            font-size: 1.8rem;
            font-weight: 600;
            color: #4b4b4b;
        }


        /*======================================
        BLUE SHOWCASE SECTION
        ======================================*/

        .rgu-rf-showcase {
            background:
                linear-gradient(135deg,
                    #254274 0%,
                    #17335e 100%);

            border-radius: 8rem 8rem 0 0;

            padding: 8rem 0;

            overflow: hidden;
        }


        /*======================================
        LEFT TABS
        ======================================*/

        .rgu-rf-tabs {
            display: flex;
            flex-direction: column;
            gap: 1rem;

            padding-right: 4rem;
        }

        .rgu-rf-tab {
            width: 100%;

            background: rgba(255, 255, 255, .02);

            border: 1px solid rgba(255, 255, 255, .14);

            box-shadow:
                inset 0 0 0 1px rgba(255, 255, 255, .03);

            color: #ffffff;

            text-align: left;

            font-family: 'Times New Roman', Times, serif;
            font-size: 1.8rem;
            font-weight: 600;
            text-transform: uppercase;

            padding: 2.2rem 2rem;

            border-radius: 1.5rem;

            cursor: pointer;

            transition: all .35s ease;
        }

        .rgu-rf-tab:hover {
            background: rgba(255, 255, 255, .04);

            border-color: rgba(255, 255, 255, .22);

            transform: translateX(6px);
        }

        .rgu-rf-tab.active {
            background: #d95b28;

            border-color: rgba(255, 255, 255, .12);

            color: #ffffff;

            box-shadow:
                0 15px 30px rgba(0, 0, 0, .18);
        }

        .rgu-rf-tab.active:hover {
            transform: none;
        }


        /*======================================
        RIGHT CONTENT
        ======================================*/

        .rgu-rf-content {
            padding-left: 2rem;
        }


        /*======================================
        CARDS
        ======================================*/

        .rgu-rf-card {
            text-align: center;
        }

        .rgu-rf-card-image {
            overflow: hidden;

            border-radius: 2.8rem;

            background: #ffffff;

            margin-bottom: 2rem;
        }

        .rgu-rf-card-image img {
            width: 100%;

            aspect-ratio: 1/1;

            object-fit: cover;

            display: block;

            transition: transform .45s ease;
        }

        .rgu-rf-card:hover .rgu-rf-card-image img {
            transform: scale(1.05);
        }

        .rgu-rf-card-name {
            margin: 0;

            font-family: 'Playfair Display', serif;
            font-size: 2rem;
            font-weight: 700;
            line-height: 1.4;

            color: #ffffff;
        }


        /*======================================
        PAGINATION
        ======================================*/

        .rgu-rf-pagination-wrap {
            margin-top: 5rem;

            display: flex;
            justify-content: center;
        }

        .rgu-rf-pagination {
            display: flex;
            align-items: center;
            gap: 1.4rem;
        }

        .rgu-rf-page-btn {
            background: none;
            border: none;

            color: rgba(255, 255, 255, .55);

            font-family: 'Times New Roman', Times, serif;
            font-size: 1.6rem;
            font-weight: 600;

            cursor: pointer;

            transition: .3s;
        }

        .rgu-rf-page-btn:hover {
            color: #ffffff;
        }

        .rgu-rf-page-btn.active {
            color: #ffffff;
        }

        .rgu-rf-page-divider {
            color: rgba(255, 255, 255, .35);

            font-size: 1.5rem;
        }


        /*======================================
        TABLET
        ======================================*/

        @media(max-width:991px) {

            .rgu-rf-tabs {
                display: flex;
                flex-direction: row;
                flex-wrap: nowrap;
                overflow-x: auto;
                overflow-y: hidden;

                gap: 1.2rem;

                padding-right: 0;
                margin-bottom: 4rem;

                scrollbar-width: none;
                -ms-overflow-style: none;
            }

            .rgu-rf-tabs::-webkit-scrollbar {
                display: none;
            }

            .rgu-rf-tab {
                flex: 0 0 auto;

                width: auto;
                min-width: unset;

                padding: 1.4rem 2rem;

                border-radius: 1.6rem;

                font-size: 1.4rem;
                line-height: 1.2;

                white-space: nowrap;

                transform: none !important;
            }

            .rgu-rf-tab:hover {
                transform: none;
            }

            .rgu-rf-content {
                padding-left: 0;
            }

        }


        /*======================================
        MOBILE
        ======================================*/

        @media(max-width:767px) {

            .rgu-rf-quote-wrap {
                padding: 5rem 0;
            }

            .rgu-rf-quote {
                font-size: 2.4rem;
            }

            .rgu-rf-quote-icon i {
                font-size: 4rem;
            }

            .rgu-rf-quote-author {
                font-size: 1.6rem;
            }

            .rgu-rf-showcase {
                border-radius: 3rem 3rem 0 0;

                padding: 5rem 0;
            }

            .rgu-rf-tab {
                min-width: 190px;

                padding: 1.8rem 2.2rem;

                font-size: 1.4rem;

                border-radius: 1.6rem;
            }

            .rgu-rf-card-image {
                border-radius: 2rem;
            }

            .rgu-rf-card-name {
                font-size: 1.8rem;
            }

            .rgu-rf-page-btn {
                font-size: 1.4rem;
            }

        }
    </style>

    <script>
        /*======================================
                ROYAL FOOTPRINTS DATA
                ======================================*/

        const rguRfData = {

            "Bharat Ratna": [

                {
                    name: "Dr. A.P.J. Abdul Kalam",
                    image: "/home-banner/footprint-list/apjabdulkalam.jpeg"
                }

            ],


            "Padma Vibhushan": [

                {
                    name: "Sri Sri Ravi Shankar",
                    image: "/home-banner/footprint-list/Gurudev-Sri-Sri-Ravi-Shankar.png"
                },

                {
                    name: "Dr. Sonal Mansingh",
                    image: "/home-banner/footprint-list/Dr.%20Sonal%20Mansingh.jpg"
                }

            ],


            "Padma Bhushan": [

                {
                    name: "Ruskin Bond",
                    image: "/home-banner/footprint-list/rgu-visitors2.010.jpeg"
                },
                {
                    name: "Shyama Chona",
                    image: "/home-banner/footprint-list/rgu-visitors2.006.jpeg"
                },
                {
                    name: "Meghnad Desai",
                    image: "/home-banner/footprint-list/rgu-visitors2.008.jpeg"
                },
                {
                    name: "Kapil Dev",
                    image: "/home-banner/footprint-list/rgu-visitors2.007.jpeg"
                }

            ],


            "Padma Shri": [

                {
                    name: "Patricia Mukhim",
                    image: "/home-banner/footprint-list/rgu-visitors2.020.jpeg"
                },
                {
                    name: "Jadav Payeng",
                    image: "/home-banner/footprint-list/rgu-visitors2.016.jpeg"
                },
                {
                    name: "Geeta Dharmarajan",
                    image: "/home-banner/footprint-list/rgu-visitors2.014.jpeg"
                },
                {
                    name: "Ileana Citaristi",
                    image: "/home-banner/footprint-list/rgu-visitors2.015.jpeg"
                },
                {
                    name: "Mamang Dai",
                    image: "/home-banner/footprint-list/rgu-visitors2.018.jpeg"
                },
                {
                    name: "Shekhar Sen",
                    image: "/home-banner/footprint-list/rgu-visitors2.023.jpeg"
                },
                {
                    name: "Shovana Narayan",
                    image: "/home-banner/footprint-list/rgu-visitors2.024.jpeg"
                },
                {
                    name: "Nirupam Bajpai",
                    image: "/home-banner/footprint-list/rgu-visitors2.011.jpeg"
                },
                {
                    name: "Soma Ghosh",
                    image: "/home-banner/footprint-list/rgu-visitors2.013.jpeg"
                },
                {
                    name: "Ravi Kannan R",
                    image: "/home-banner/footprint-list/rgu-visitors2.017.jpeg"
                },
                {
                    name: "Uddhab Bharali",
                    image: "/home-banner/footprint-list/rgu-visitors2.027.jpeg"
                },
                {
                    name: "Dr. Kiran Seth",
                    image: "/home-banner/footprint-list/footprint-seth.jpg"
                },
                {
                    name: "Prof. Anil Kumar Boro",
                    image: "/home-banner/footprint-list/prof-anil-boro.jpg"
                }

            ],


            "Arjuna Award": [

                {
                    name: "Hima Das",
                    image: "/home-banner/footprint-list/rgu-visitors2.001.jpeg"
                },
                {
                    name: "Suresh Kumar Mishra",
                    image: "/home-banner/footprint-list/rgu-visitors2.003.jpeg"
                },
                {
                    name: "Lovlina Borgohain",
                    image: "/home-banner/footprint-list/footprint072024.026.jpeg"
                },


            ],


            "Other Luminaries": [

                {
                    name: "Jagdeep Dhankhar Ji",
                    image: "/home-banner/footprint-list/Jagdeep-Dhankhar.jpg"
                },
                {
                    name: "Justice Ranjan Gogoi",
                    image: "/home-banner/footprint-list/Ranjan-Gogoi.png"
                },
                {
                    name: "Zubeen Garg",
                    image: "/home-banner/footprint-list/rgu-visitors.049.jpeg"
                },
                {
                    name: "Sri Sri Ravi Shankar",
                    image: "/home-banner/footprint-list/ashoksinghal-footprints.jpg"
                },
                {
                    name: "Subhash Ghai",
                    image: "/home-banner/footprint-list/rgu-visitors.045.jpeg"
                },
                {
                    name: "Subhash Chandra",
                    image: "/home-banner/footprint-list/rgu-visitors.044.jpeg"
                },
                {
                    name: "Siddharth Mohan",
                    image: "/home-banner/footprint-list/rgu-visitors.029.jpeg"
                },
                {
                    name: "Adil Hussain",
                    image: "/home-banner/footprint-list/rgu-visitors.002.jpeg"
                },
                {
                    name: "Prof. Jagdish Mukhi",
                    image: "/home-banner/footprint-list/rgu-visitors.026.jpeg"
                },
                {
                    name: "Bickram Ghosh",
                    image: "/home-banner/footprint-list/rgu-visitors.005.jpeg"
                },
                {
                    name: "Rima Das",
                    image: "/home-banner/footprint-list/rgu-visitors.028.jpeg"
                },
                {
                    name: "Navin Chawla",
                    image: "/home-banner/footprint-list/rgu-visitors.024.jpeg"
                },
                {
                    name: "Maxwell Pereira",
                    image: "/home-banner/footprint-list/rgu-visitors.021.jpeg"
                },
                {
                    name: "Lou Majaw",
                    image: "/home-banner/footprint-list/rgu-visitors.020.jpeg"
                },
                {
                    name: "Sarbananda Sonowal",
                    image: "/home-banner/footprint-list/rgu-visitors.050.jpeg"
                },
                {
                    name: "Shiv Khera",
                    image: "/home-banner/footprint-list/rgu-visitors.043.jpeg"
                },
                {
                    name: "Subramanian Swamy",
                    image: "/home-banner/footprint-list/rgu-visitors.046.jpeg"
                },
                {
                    name: "Tarun Gogoi",
                    image: "/home-banner/footprint-list/rgu-visitors.019.jpeg"
                },
                {
                    name: "Jerry Pinto",
                    image: "/home-banner/footprint-list/rgu-visitors.018.jpeg"
                },
                {
                    name: "Shashi Tharoor",
                    image: "/home-banner/footprint-list/rgu-visitors.013.jpeg"
                },
                {
                    name: "Jatin Bora",
                    image: "/home-banner/footprint-list/rgu-visitors.017.jpeg"
                },
                {
                    name: "Arnab Goswami",
                    image: "/home-banner/footprint-list/rgu-visitors.030.jpeg"
                },
                {
                    name: "Mani Shankar Aiyar",
                    image: "/home-banner/footprint-list/rgu-visitors.037.jpeg"
                },
                {
                    name: "Deepak Vohra",
                    image: "/home-banner/footprint-list/rgu-visitors.007.jpeg"
                },

                {
                    name: "Prafulla Kumar Mahanta",
                    image: "/home-banner/footprint-list/rgu-visitors.039.jpeg"
                },
                {
                    name: "Chetan Bhagat",
                    image: "/home-banner/footprint-list/rgu-visitors.033.jpeg"
                },
                {
                    name: "Dipak C. Jain",
                    image: "/home-banner/footprint-list/rgu-visitors.034.jpeg"
                },
                {
                    name: "Himanshu Rai",
                    image: "/home-banner/footprint-list/rgu-visitors.015.jpeg"
                },
                {
                    name: "Baba Ramdev",
                    image: "/home-banner/footprint-list/rgu-visitors.003.jpeg"
                },
                {
                    name: "Dr. Himanta Biswa Sarma",
                    image: "/home-banner/footprint-list/rgu-visitors.010.jpeg"
                },
                {
                    name: "Binita Jain",
                    image: "/home-banner/footprint-list/rgu-visitors.006.jpeg"
                },
                {
                    name: "Chungsik Yong",
                    image: "/home-banner/footprint-list/rgu-visitors.008.jpeg"
                },
                {
                    name: "Dr. Easterine Kire",
                    image: "/home-banner/footprint-list/rgu-visitors.009.jpeg"
                },
                {
                    name: "Dr. N C Talukdar",
                    image: "/home-banner/footprint-list/rgu-visitors.011.jpeg"
                },
                {
                    name: "Pawan Agarwal",
                    image: "/home-banner/footprint-list/rgu-visitors.012.jpeg"
                },
                {
                    name: "Haseeb A Drabu",
                    image: "/home-banner/footprint-list/rgu-visitors.014.jpeg"
                },
                {
                    name: "Kazi M Murshed",
                    image: "/home-banner/footprint-list/rgu-visitors.022.jpeg"
                },
                {
                    name: "Sunita Menon",
                    image: "/home-banner/footprint-list/rgu-visitors.023.jpeg"
                },
                {
                    name: "Anil Sahasrabudhe",
                    image: "/home-banner/footprint-list/rgu-visitors.025.jpeg"
                },
                {
                    name: "Dr. Ved Prakash",
                    image: "/home-banner/footprint-list/rgu-visitors.027.jpeg"
                },
                {
                    name: "Badruddin Ajmal",
                    image: "/home-banner/footprint-list/rgu-visitors.031.jpeg"
                },
                {
                    name: "Bhubaneswar Kalita",
                    image: "/home-banner/footprint-list/rgu-visitors.032.jpeg"
                },
                {
                    name: "Mahesh Bhatt",
                    image: "/home-banner/footprint-list/rgu-visitors.036.jpeg"
                },
                {
                    name: "Pijush Hazarika",
                    image: "/home-banner/footprint-list/rgu-visitors.038.jpeg"
                },
                {
                    name: "Ram Madhav",
                    image: "/home-banner/footprint-list/rgu-visitors.040.jpeg"
                },
                {
                    name: "Ranjit S. Mooshahary",
                    image: "/home-banner/footprint-list/rgu-visitors.041.jpeg"
                },
                {
                    name: "Shiv Charan Mathur",
                    image: "/home-banner/footprint-list/footprint072024.002.jpeg"
                },
                {
                    name: "Gulab Chand Kataria",
                    image: "/home-banner/footprint-list/footprint072024.017.jpeg"
                },

                {
                    name: "Vikram Doraiswami",
                    image: "/home-banner/footprint-list/footprint072024.005.jpeg"
                },
                {
                    name: "Janaki Ballabh Patnaik",
                    image: "/home-banner/footprint-list/footprint072024.016.jpeg"
                },
                {
                    name: "Bhushan Patwardhan",
                    image: "/home-banner/footprint-list/footprint072024.022.jpeg"
                },
                {
                    name: "Prof. C. Raj Kumar",
                    image: "/home-banner/footprint-list/footprint072024.011.jpeg"
                },
                {
                    name: "Sheel Vardhan Singh",
                    image: "/home-banner/footprint-list/footprint072024.007.jpeg"
                },
                {
                    name: "Ashneer Grover",
                    image: "/home-banner/footprint-list/footprint072024.023.jpeg"
                },
                {
                    name: "Aman Gupta",
                    image: "/home-banner/footprint-list/footprint072024.025.jpeg"
                },
                {
                    name: "Justice Ujjal Bhuyan",
                    image: "/home-banner/footprint-list/footprint072024.006.jpeg"
                },
                {
                    name: "Prof. D.P. Agrawal",
                    image: "/home-banner/footprint-list/footprint072024.021.jpeg"
                },
                {
                    name: "Justice V. Ramasubramanian",
                    image: "/home-banner/footprint-list/footprint072024.015.jpeg"
                },
                {
                    name: "Digvijaya Singh",
                    image: "/home-banner/footprint-list/footprint072024.019.jpeg"
                },
                {
                    name: "Sanjeev Sanyal",
                    image: "/home-banner/footprint-list/footprint072024.003.jpeg"
                },
                {
                    name: "Devdutt Pattnaik",
                    image: "/home-banner/footprint-list/footprint072024.020.jpeg"
                },
                {
                    name: "Barry O’Brien",
                    image: "/home-banner/footprint-list/footprint072024.004.jpeg"
                },
                {
                    name: "Nitin Gadkari",
                    image: "/home-banner/footprint-list/footprint072024.013.jpeg"
                },
                {
                    name: "Sonu Sharma",
                    image: "/home-banner/footprint-list/footprint072024.001.jpeg"
                },
                {
                    name: "Ranoj Pegu",
                    image: "/home-banner/footprint-list/footprint072024.009.jpeg"
                },
                {
                    name: "Om Birla",
                    image: "/home-banner/footprint-list/footprint072024.012.jpeg"
                },
                {
                    name: "Nandita Garlosa",
                    image: "/home-banner/footprint-list/footprint072024.014.jpeg"
                },
                {
                    name: "Dr. Malabika Mitra",
                    image: "/home-banner/footprint-list/footprint072024.018.jpeg"
                },
                {
                    name: "Pt. Rakesh Chaurasia",
                    image: "/home-banner/footprint-list/footprint072024.010.jpeg"
                },
                {
                    name: "Riyan Parag",
                    image: "/home-banner/footprint-list/footprint072024.008.jpeg"
                },
                {
                    name: "Armaan Malik",
                    image: "/home-banner/footprint-list/Armaan-Malik.jpg"
                },
                {
                    name: "Prof. Prabuddha Ganguli",
                    image: "/home-banner/footprint-list/Prof-Prabuddha-Ganguli.jpg"
                },

                {
                    name: "Temjen Imna Along",
                    image: "/home-banner/footprint-list/Temjen-Imna-Along.jpg"
                },
                {
                    name: "Pradeep Purohit",
                    image: "/home-banner/footprint-list/Pradeep-Purohit.jpg"
                },
                {
                    name: "Prof. Amarjyoti Choudhury",
                    image: "/home-banner/footprint-list/Prof-Amarjyoti-Choudhury.jpg"
                },
                {
                    name: "Maj. Gen. Rajesh Kumar Jha",
                    image: "/home-banner/footprint-list/Maj-Gen-Rajesh-Kumar-Jha.jpg"
                },
                {
                    name: "Mushtaq Ahmed Anfar Ali",
                    image: "/home-banner/footprint-list/Mushtaq-Ahmed-Anfar-Ali.jpg"
                },
                {
                    name: "Conrad K Sangma",
                    image: "/home-banner/footprint-list/Conrad-K-Sangma.jpg"
                },
                {
                    name: "Dr. Arup Kumar Misra",
                    image: "/home-banner/footprint-list/Dr-Arup-Kumar-Misra.jpg"
                },
                {
                    name: "Lt. Gen. Rana Pratap Kalita",
                    image: "/home-banner/footprint-list/Lt-Gen-Rana-Pratap-Kalita.jpg"
                },
                {
                    name: "Bubagra Pradyot Bikram Manikya",
                    image: "/home-banner/footprint-list/Bubagra-Pradyot-Bikram-Manikya.jpg"
                },
                {
                    name: "Chaitali Panmei",
                    image: "/home-banner/footprint-list/Chaitali-Panmei.jpg"
                },
                {
                    name: "Barsha Rani Bishaya",
                    image: "/home-banner/footprint-list/Barsha-Rani-Bishaya.jpg"
                },
                {
                    name: "Shillong Chamber Choir",
                    image: "/home-banner/footprint-list/rgu-visitor-group.001.jpeg"
                },


            ]

        };


        /*======================================
        CONFIGURATION
        ======================================*/

        const rguRfCardsPerPage = 2;

        const rguRfTabs = Object.keys(rguRfData);

        /*
        Each category remembers its own page.
        Example:
        {
            "Padma Shri": 2,
            "Bharat Ratna": 1
        }
        */

        const rguRfCurrentPages = {};

        rguRfTabs.forEach(tab => {
            rguRfCurrentPages[tab] = 1;
        });


        /* Default Active Tab */

        let rguRfActiveTab = rguRfTabs[0];
    </script>

    <script>
        /*======================================
                ROYAL FOOTPRINTS LOGIC
                ======================================*/

        const rguRfTabsContainer =
            document.getElementById("rguRfTabs");

        const rguRfCardsContainer =
            document.getElementById("rguRfCards");

        const rguRfPaginationContainer =
            document.getElementById("rguRfPagination");


        /*======================================
        RENDER TABS
        ======================================*/

        function rguRfRenderTabs() {

            rguRfTabsContainer.innerHTML = "";

            rguRfTabs.forEach(tab => {

                const button =
                    document.createElement("button");

                button.className =
                    `rgu-rf-tab ${tab === rguRfActiveTab
                        ? "active"
                        : ""
                    }`;

                button.textContent = tab;

                button.addEventListener(
                    "click",
                    () => {

                        rguRfActiveTab = tab;

                        rguRfRender();

                    }
                );

                rguRfTabsContainer.appendChild(
                    button
                );

            });

        }


        /*======================================
        RENDER CARDS
        ======================================*/

        function rguRfRenderCards() {

            const people =
                rguRfData[rguRfActiveTab];

            const currentPage =
                rguRfCurrentPages[
                    rguRfActiveTab
                ];

            const start =
                (currentPage - 1) *
                rguRfCardsPerPage;

            const visiblePeople =
                people.slice(
                    start,
                    start + rguRfCardsPerPage
                );


            rguRfCardsContainer.innerHTML = "";


            /* Layout */

            if (visiblePeople.length === 1) {

                rguRfCardsContainer.className =
                    "row justify-content-center g-4";

            } else {

                rguRfCardsContainer.className =
                    "row g-4";

            }


            visiblePeople.forEach(person => {

                const column =
                    document.createElement("div");

                column.className =
                    visiblePeople.length === 1 ?
                    "col-lg-6 col-md-8" :
                    "col-lg-6 col-md-6";


                column.innerHTML = `

            <div class="rgu-rf-card">

                <div class="rgu-rf-card-image">

                    <img src="${person.image}"
                         alt="${person.name}">

                </div>

                <h4 class="rgu-rf-card-name">

                    ${person.name}

                </h4>

            </div>

        `;

                rguRfCardsContainer.appendChild(
                    column
                );

            });

        }


        /*======================================
        PAGINATION HELPERS
        ======================================*/

        function rguRfCreatePageButton(
            page,
            isActive = false
        ) {

            const button =
                document.createElement("button");

            button.className =
                `rgu-rf-page-btn ${isActive ? "active" : ""
                }`;

            button.textContent =
                String(page).padStart(2, "0");

            button.addEventListener(
                "click",
                () => {

                    rguRfCurrentPages[
                        rguRfActiveTab
                    ] = page;

                    rguRfRender();

                }
            );

            return button;

        }


        function rguRfCreateDivider(
            text = "|"
        ) {

            const divider =
                document.createElement("span");

            divider.className =
                "rgu-rf-page-divider";

            divider.textContent = text;

            return divider;

        }


        /*======================================
        RENDER PAGINATION
        ======================================*/

        function rguRfRenderPagination() {

            rguRfPaginationContainer.innerHTML =
                "";

            const people =
                rguRfData[rguRfActiveTab];

            const totalPages =
                Math.ceil(
                    people.length /
                    rguRfCardsPerPage
                );

            const currentPage =
                rguRfCurrentPages[
                    rguRfActiveTab
                ];


            /* Hide if only one page */

            if (totalPages <= 1) {

                return;

            }


            /* Previous */

            const prevBtn =
                document.createElement("button");

            prevBtn.className =
                "rgu-rf-page-btn";

            prevBtn.innerHTML = "&laquo;";

            prevBtn.disabled =
                currentPage === 1;

            prevBtn.style.opacity =
                currentPage === 1 ?
                ".35" :
                "1";

            prevBtn.addEventListener(
                "click",
                () => {

                    if (currentPage > 1) {

                        rguRfCurrentPages[
                            rguRfActiveTab
                        ]--;

                        rguRfRender();

                    }

                }
            );

            rguRfPaginationContainer.appendChild(
                prevBtn
            );


            /*======================================
            SMART WINDOW
            ======================================*/

            const maxVisible = 5;

            let startPage;
            let endPage;


            if (totalPages <= maxVisible) {

                startPage = 1;
                endPage = totalPages;

            } else {

                startPage =
                    currentPage - 2;

                endPage =
                    currentPage + 2;


                if (startPage < 1) {

                    startPage = 1;
                    endPage = maxVisible;

                }


                if (
                    endPage > totalPages
                ) {

                    endPage = totalPages;

                    startPage =
                        totalPages -
                        maxVisible +
                        1;

                }

            }


            /* First Page */

            if (startPage > 1) {

                rguRfPaginationContainer.appendChild(
                    rguRfCreateDivider()
                );

                rguRfPaginationContainer.appendChild(
                    rguRfCreatePageButton(
                        1,
                        currentPage === 1
                    )
                );

                if (startPage > 2) {

                    rguRfPaginationContainer.appendChild(
                        rguRfCreateDivider(
                            "..."
                        )
                    );

                }

            }


            /* Visible Pages */

            for (
                let i = startPage; i <= endPage; i++
            ) {

                rguRfPaginationContainer.appendChild(
                    rguRfCreateDivider()
                );

                rguRfPaginationContainer.appendChild(
                    rguRfCreatePageButton(
                        i,
                        i === currentPage
                    )
                );

            }


            /* Last Page */

            if (endPage < totalPages) {

                if (
                    endPage <
                    totalPages - 1
                ) {

                    rguRfPaginationContainer.appendChild(
                        rguRfCreateDivider(
                            "..."
                        )
                    );

                }

                rguRfPaginationContainer.appendChild(
                    rguRfCreateDivider()
                );

                rguRfPaginationContainer.appendChild(
                    rguRfCreatePageButton(
                        totalPages,
                        currentPage === totalPages
                    )
                );

            }


            /* Next */

            rguRfPaginationContainer.appendChild(
                rguRfCreateDivider()
            );

            const nextBtn =
                document.createElement("button");

            nextBtn.className =
                "rgu-rf-page-btn";

            nextBtn.innerHTML = "&raquo;";

            nextBtn.disabled =
                currentPage === totalPages;

            nextBtn.style.opacity =
                currentPage === totalPages ?
                ".35" :
                "1";

            nextBtn.addEventListener(
                "click",
                () => {

                    if (
                        currentPage <
                        totalPages
                    ) {

                        rguRfCurrentPages[
                            rguRfActiveTab
                        ]++;

                        rguRfRender();

                    }

                }
            );

            rguRfPaginationContainer.appendChild(
                nextBtn
            );

        }


        /*======================================
        MASTER RENDER
        ======================================*/

        function rguRfRender() {

            rguRfRenderTabs();

            rguRfRenderCards();

            rguRfRenderPagination();

        }


        /*======================================
        INITIALIZE
        ======================================*/

        document.addEventListener(
            "DOMContentLoaded",
            () => {

                rguRfRender();

            }
        );
    </script>
@endsection
